// Generated by scripts/extract-engines.mjs. Do not edit.
// Released AI engines, newest first. "options" are the AI settings the engine
// reads; the UI disables the rest while it is selected.

/**
 * @typedef {object} AIEngine
 * @property {string} id       version shown in the menu and used in room ids
 * @property {string} date     release date
 * @property {string} tag      git tag the engine was extracted from
 * @property {string} commit
 * @property {string[]} options
 * @property {() => Promise<any>} load  resolves to the engine's physics module
 */

/** @type {AIEngine[]} */
export const AI_ENGINES = [
  {
    id: '8.0',
    date: '2026-04-13',
    tag: 'v8.0.20260413',
    commit: 'dc011bc',
    options: [
      'anti_block',
      'block',
      'defense',
      'delay',
      'diving',
      'early_ball',
      'fancy',
      'jump',
      'serve',
    ],
    load: () => import(/* webpackChunkName: "ai-8.0" */ '../physics.js'),
  },
  {
    id: '7.0',
    date: '2024-12-10',
    tag: 'v7.0.20241210',
    commit: '3df47f3',
    options: [
      'anti_block',
      'block',
      'defense',
      'delay',
      'diving',
      'early_ball',
      'fancy',
      'jump',
      'serve',
    ],
    load: () => import(/* webpackChunkName: "ai-7.0" */ './v7.0/physics.js'),
  },
  {
    id: '6.0',
    date: '2023-08-16',
    tag: 'v6.0.20230816',
    commit: 'd4f9d40',
    options: [
      'anti_block',
      'block',
      'defense',
      'delay',
      'diving',
      'early_ball',
      'fancy',
      'jump',
      'serve',
    ],
    load: () => import(/* webpackChunkName: "ai-6.0" */ './v6.0/physics.js'),
  },
  {
    id: '5.0',
    date: '2023-01-19',
    tag: 'v5.0.20230119',
    commit: '6451e02',
    options: [
      'anti_block',
      'block',
      'defense',
      'diving',
      'early_ball',
      'fancy',
      'jump',
      'serve',
    ],
    load: () => import(/* webpackChunkName: "ai-5.0" */ './v5.0/physics.js'),
  },
  {
    id: '4.2',
    date: '2022-12-17',
    tag: 'v4.2.20221217',
    commit: '7ab2056',
    options: [
      'anti_block',
      'block',
      'defense',
      'diving',
      'early_ball',
      'fancy',
      'jump',
      'serve',
    ],
    load: () => import(/* webpackChunkName: "ai-4.2" */ './v4.2/physics.js'),
  },
  {
    id: '4.1',
    date: '2022-11-13',
    tag: 'v4.1.20221113',
    commit: '594baae',
    options: ['block', 'diving', 'fancy', 'jump', 'serve'],
    load: () => import(/* webpackChunkName: "ai-4.1" */ './v4.1/physics.js'),
  },
  {
    id: '4.0',
    date: '2022-09-25',
    tag: 'v4.0.20220925',
    commit: '350cac9',
    options: ['block', 'diving', 'fancy', 'jump', 'serve'],
    load: () => import(/* webpackChunkName: "ai-4.0" */ './v4.0/physics.js'),
  },
  {
    id: '3.0',
    date: '2022-09-03',
    tag: 'v3.0.20220903',
    commit: '5b34da9',
    options: ['block', 'diving', 'fancy', 'jump', 'serve'],
    load: () => import(/* webpackChunkName: "ai-3.0" */ './v3.0/physics.js'),
  },
  {
    id: '2.0',
    date: '2022-05-22',
    tag: 'v2.0.20220522',
    commit: '8c4a26d',
    options: [],
    load: () => import(/* webpackChunkName: "ai-2.0" */ './v2.0/physics.js'),
  },
  {
    id: '1.1',
    date: '2022-05-02',
    tag: 'v1.1.20220502',
    commit: '746b6bd',
    options: [],
    load: () => import(/* webpackChunkName: "ai-1.1" */ './v1.1/physics.js'),
  },
  {
    id: '1.0',
    date: '2022-04-23',
    tag: 'v1.0.20220423',
    commit: '9a625ef',
    options: [],
    load: () => import(/* webpackChunkName: "ai-1.0" */ './v1.0/physics.js'),
  },
];

/** The engine bundled into the main page (src/resources/js/physics.js). */
export const DEFAULT_AI_ENGINE = AI_ENGINES[0];
