// Generated by scripts/extract-engines.mjs. Do not edit.
// Gives this engine the names it imports from ui.js, read live from today's UI.
import * as ui from '../../ui.js';

export {
  SkillTypeForPlayer1Available,
  SkillTypeForPlayer2Available,
} from '../../ui.js';

// Random serve order. The fixed-order switch was dropped from the UI in 7.0.
export const serveMode = 0;

// "freestyle" was renamed "fancy" in 4.0; 4.2-5.0's "close_defense" checkbox
// became defense mode 4 (predict, close) in 6.0.
export const capability = new Proxy(
  {},
  {
    get(_, key) {
      if (key === 'freestyle') return ui.capability.fancy;
      if (key === 'close_defense') return Number(ui.defense) === 4;
      return ui.capability[key];
    },
  }
);

export { delay, defense } from '../../ui.js';
