#!/usr/bin/env node
/**
 * Extract every released AI engine from the git tags so the game can switch
 * between them at runtime ("AI 版本" in the menu bar).
 *
 * For each tag vX.Y.YYYYMMDD this writes src/resources/js/engines/vX.Y/:
 *   physics.js  the tag's src/resources/js/physics.js, byte for byte
 *   ui.js       a shim exporting what that engine imports from ui.js, read
 *               from today's settings (renamed and retired options mapped)
 *   rand.js     re-exports today's rand.js
 * and regenerates src/resources/js/engines/index.js, the registry the UI
 * reads: id, date, tag, commit, which options the engine looks at, loader;
 * the version list in src/version.html; and src/_redirects, which sends the
 * old /version/<code>/ builds to the same AI in today's game.
 *
 * The newest tag is served by src/resources/js/physics.js itself as long as
 * that file is unchanged since the tag; once main moves on, the tag is
 * extracted like the others and main's engine is listed as "dev".
 *
 * Run after tagging a release:  node scripts/extract-engines.mjs
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(
  path.dirname(new URL(import.meta.url).pathname),
  '..'
);
const jsDir = path.join(root, 'src/resources/js');
const enginesDir = path.join(jsDir, 'engines');
const PHYSICS = 'src/resources/js/physics.js';

const git = (...args) =>
  execFileSync('git', args, {
    cwd: root,
    encoding: 'utf8',
    maxBuffer: 64 << 20,
  });

const tags = git('tag', '--list', 'v*')
  .split('\n')
  .filter((t) => /^v\d+\.\d+\.\d{8}$/.test(t))
  .sort((a, b) => {
    const pa = a.slice(1).split('.').map(Number);
    const pb = b.slice(1).split('.').map(Number);
    return pa[0] - pb[0] || pa[1] - pb[1];
  });
if (tags.length === 0)
  throw new Error('no vX.Y.YYYYMMDD tags found; fetch tags first');

/** What an engine reads from ui.js, and which UI options that makes meaningful. */
function analyse(source) {
  const importMatch = source.match(/import\s*{([^}]*)}\s*from\s*'\.\/ui\.js'/);
  const imports = importMatch
    ? importMatch[1]
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
    : [];
  const capabilityKeys = [
    ...new Set([...source.matchAll(/capability\.([a-z_]+)/g)].map((m) => m[1])),
  ].sort();
  // Map the engine's names onto today's option ids.
  const options = new Set();
  for (const key of capabilityKeys) {
    if (key === 'freestyle') options.add('fancy');
    else if (key === 'close_defense') options.add('defense');
    else options.add(key);
  }
  if (imports.includes('delay')) options.add('delay');
  if (imports.includes('defense')) options.add('defense');
  return { imports, capabilityKeys, options: [...options].sort() };
}

const UI_SHIM = (
  imports
) => `// Generated by scripts/extract-engines.mjs. Do not edit.
// Gives this engine the names it imports from ui.js, read live from today's UI.
${imports.includes('capability') ? "import * as ui from '../../ui.js';\n" : ''}
export { SkillTypeForPlayer1Available, SkillTypeForPlayer2Available } from '../../ui.js';
${
  imports.includes('serveMode')
    ? `
// Random serve order. The fixed-order switch was dropped from the UI in 7.0.
export const serveMode = 0;
`
    : ''
}${
  imports.includes('capability')
    ? `
// "freestyle" was renamed "fancy" in 4.0; 4.2-5.0's "close_defense" checkbox
// became defense mode 4 (predict, close) in 6.0.
export const capability = new Proxy(
  {},
  {
    get(_, key) {
      if (key === 'freestyle') return ui.capability.fancy;
      if (key === 'close_defense') return Number(ui.defense) === 4;
      return ui.capability[key];
    },
  }
);
`
    : ''
}${
  imports.includes('delay') || imports.includes('defense')
    ? `
export { delay, defense } from '../../ui.js';
`
    : ''
}`;

const RAND_SHIM = `// Generated by scripts/extract-engines.mjs. Do not edit.
export { rand, true_rand } from '../../rand.js';
`;

fs.rmSync(enginesDir, { recursive: true, force: true });
fs.mkdirSync(enginesDir, { recursive: true });

const current = fs.readFileSync(path.join(root, PHYSICS), 'utf8');
const entries = [];
for (const [i, tag] of tags.entries()) {
  const [, id, date] = tag.match(/^v(\d+\.\d+)\.(\d{8})$/);
  const commit = git('rev-list', '-n1', tag).trim().slice(0, 7);
  const source = git('show', `${tag}:${PHYSICS}`);
  const info = analyse(source);
  const newest = i === tags.length - 1;
  const entry = {
    id,
    date: `${date.slice(0, 4)}-${date.slice(4, 6)}-${date.slice(6)}`,
    tag,
    commit,
    options: info.options,
  };
  if (newest && source === current) {
    entry.module = '../physics.js';
  } else {
    const dir = path.join(enginesDir, `v${id}`);
    fs.mkdirSync(dir);
    fs.writeFileSync(path.join(dir, 'physics.js'), source);
    fs.writeFileSync(path.join(dir, 'ui.js'), UI_SHIM(info.imports));
    fs.writeFileSync(path.join(dir, 'rand.js'), RAND_SHIM);
    entry.module = `./v${id}/physics.js`;
  }
  entries.push(entry);
}
if (entries.at(-1).module !== '../physics.js') {
  // main has engine changes not yet released under a tag.
  entries.push({
    id: 'dev',
    date: '',
    tag: '',
    commit: git('rev-parse', '--short=7', 'HEAD').trim(),
    options: analyse(current).options,
    module: '../physics.js',
  });
}
entries.reverse(); // newest first, as the menu lists them

const registry = `// Generated by scripts/extract-engines.mjs. Do not edit.
// Released AI engines, newest first. "options" are the AI settings the engine
// reads; the UI disables the rest while it is selected.

/**
 * @typedef {object} AIEngine
 * @property {string} id       version shown in the menu and used in room ids
 * @property {string} date     release date
 * @property {string} tag      git tag the engine was extracted from
 * @property {string} commit
 * @property {string[]} options
 * @property {() => Promise<any>} load  resolves to the engine's physics module
 */

/** @type {AIEngine[]} */
export const AI_ENGINES = [
${entries
  .map(
    (e) => `  {
    id: '${e.id}',
    date: '${e.date}',
    tag: '${e.tag}',
    commit: '${e.commit}',
    options: ${JSON.stringify(e.options)
      .replace(/"/g, "'")
      .replace(/,/g, ', ')},
    load: () => import(/* webpackChunkName: "ai-${e.id}" */ '${e.module}'),
  },`
  )
  .join('\n')}
];

/** The engine bundled into the main page (src/resources/js/physics.js). */
export const DEFAULT_AI_ENGINE = AI_ENGINES[0];
`;
fs.writeFileSync(path.join(enginesDir, 'index.js'), registry);

// version.html: one link per release, opening today's game with that AI.
const released = entries.filter((e) => e.tag);
const full = (e) => e.tag.slice(1);
const list = [
  `        <h2><a href="/">Latest: ${full(released[0])}</a></h2>`,
  ...released
    .slice(1)
    .map((e) => `        <li><a href="/en/?ai=${e.id}">${full(e)}</a></li>`),
].join('\n');
const versionHtmlPath = path.join(root, 'src/version.html');
const versionHtml = fs
  .readFileSync(versionHtmlPath, 'utf8')
  .replace(
    /<!-- ai-versions:start[^>]*-->[\s\S]*?<!-- ai-versions:end -->/,
    `<!-- ai-versions:start (generated by scripts/extract-engines.mjs) -->\n${list}\n        <!-- ai-versions:end -->`
  );
fs.writeFileSync(versionHtmlPath, versionHtml);

// _redirects (Cloudflare Pages): the old per-version builds lived under
// /version/<major><minor><date>/; send those links to the same AI in today's game.
const redirects = released.slice(1).flatMap((e) => {
  const code = e.id.replace('.', '') + e.tag.split('.').at(-1);
  return [
    `/version/${code} /en/?ai=${e.id} 301`,
    `/version/${code}/* /en/?ai=${e.id} 301`,
  ];
});
fs.writeFileSync(
  path.join(root, 'src/_redirects'),
  `# Generated by scripts/extract-engines.mjs. Do not edit.\n${redirects.join(
    '\n'
  )}\n`
);

// House style for the generated files; the physics.js copies stay verbatim.
const generated = [
  path.join(enginesDir, 'index.js'),
  ...entries
    .filter((e) => e.module !== '../physics.js')
    .flatMap((e) =>
      ['ui.js', 'rand.js'].map((f) => path.join(enginesDir, `v${e.id}`, f))
    ),
];
execFileSync(
  'npx',
  ['--no-install', 'prettier', '--write', '--loglevel', 'warn', ...generated],
  {
    cwd: root,
    stdio: 'inherit',
  }
);

for (const e of entries) {
  console.log(
    `${e.id.padEnd(4)} ${e.date || '(main)'.padEnd(10)} ${e.commit} ${
      e.module
    }  [${e.options.join(' ')}]`
  );
}
