// Generated by scripts/extract-engines.mjs. Do not edit.
// Gives this engine the names it imports from ui.js, read live from today's UI.

export {
  SkillTypeForPlayer1Available,
  SkillTypeForPlayer2Available,
} from '../../ui.js';

// Random serve order. The fixed-order switch was dropped from the UI in 7.0.
export const serveMode = 0;
